name: clean_architecture
description: A Flutter project with clean architecture
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  multiple_result: ^5.1.0
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  copy_with_extension: ^5.0.4
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  get_it: ^7.6.4
  hive: ^2.2.3
  flutter_secure_storage: ^9.0.0
  path_provider: ^2.1.1
  talker: ^3.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  copy_with_extension_gen: ^5.0.4
  hive_generator: ^2.0.1


flutter:
  uses-material-design: true
